export enum RecordCollection {
    ACCESS_CONTROLS = 'ACCESS_CONTROLS',
    ACCOUNT_PRODUCTS = 'ACCOUNT_PRODUCTS',
    ACCOUNT = 'ACCOUNT',
    ATTACHMENTS = 'ATTACHMENTS',
    CUSTOMERS = 'CUSTOMERS',
    LEADS = 'LEADS',
    PAYMENTS = 'PAYMENTS',
    ROLE_GROUPS = 'ROLE_GROUPS',
    USER_CUSTOMERS = 'USER_CUSTOMERS',
    USER_LINKS = 'USER_LINKS',
    USER_PRODUCTS = 'USER_PRODUCTS',
    USERS = 'USERS',
    WEBHOOKS = 'WEBHOOKS',
}

export enum RecordAction {
    CREATED = 'CREATED',
    UPDATED = 'UPDATED',
    DELETED = 'DELETED',
}
