export enum WebhookEventTypes {
    KYC_REJECTED = 'KYC_REJECTED',
    KYC_ACCEPTED = 'KYC_ACCEPTED',
    DIGIO_SIGN_INITIATED = 'DIGIO_SIGN_INITIATED',
    DIGIO_SIGN_SUCCESS = 'DIGIO_SIGN_SUCCESS',
    DIGIO_SIGN_FAILED = 'DIGIO_SIGN_FAILED',
    ORDER_CREATED = 'ORDER_CREATED',
    ORDER_FAILED = 'ORDER_FAILED',
    ORDER_PROCESSED = 'ORDER_PROCESSED',
    ORDER_REJECTED = 'ORDER_REJECTED',
    PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
    PAYMENT_FAILED = 'PAYMENT_FAILED',
}
